# Use case configuration for Motorola Edge 30
# Author: Val Packett <val@packett.cool>

Syntax 4

LibraryConfig.remap.Config {
	ctl.default.map."name='Amplifier Playback Volume'" {
		"name='Amplifier L PCM Playback Volume'".vindex.0 0
		"name='Amplifier R PCM Playback Volume'".vindex.1 0
	}
}

SectionUseCase."HiFi" {
	File "/Motorola/dubai/HiFi.conf"
	Comment "HiFi quality Music."
}

BootSequence [
	cset "name='HPHL Volume' 20"
	cset "name='HPHR Volume' 20"
	cset "name='ADC1 Volume' 12"
	cset "name='ADC2 Volume' 12"
	cset "name='ADC3 Volume' 12"
]

Include.card-init.File "/lib/card-init.conf"
Include.ctl-remap.File "/lib/ctl-remap.conf"
Include.wcd-init.File "/codecs/wcd937x/init.conf"
