# Use case configuration for Motorola Edge 30
# Author: Val Packett <val@packett.cool>

SectionVerb {
	EnableSequence [
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 1"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 1"
		cset "name='ADC1 Switch' 0"
		cset "name='ADC2 Switch' 0"
		cset "name='ADC3 Switch' 0"
		cset "name='ADC1_MIXER Switch' 0"
		cset "name='ADC2_MIXER Switch' 0"
	]

	DisableSequence [
		cset "name='SEN_MI2S_RX Audio Mixer MultiMedia1' 0"
		cset "name='MultiMedia3 Mixer TX_CODEC_DMA_TX_3' 0"
	]

	Value.TQ "Music"
}

SectionDevice."Speaker" {
	Comment "Speaker Playback"

	Value {
		PlaybackChannels 2
		PlaybackPriority 100
		PlaybackPCM "hw:${CardId},0"
		PlaybackMixer "default:${CardId}"
		PlaybackVolume "Amplifier Playback Volume"
	}
}

SectionDevice."Mic1" {
	Comment "Top Microphone"

	ConflictingDevice [
		"Mic3"
	]

	Include.txmhpe.File "/codecs/qcom-lpass/tx-macro/SoundwireMic0EnableSeq.conf"
	Include.txmhpd.File "/codecs/qcom-lpass/tx-macro/SoundwireMicDisableSeq.conf"

	EnableSequence [
		cset "name='ADC1_MIXER Switch' 1"
		cset "name='ADC1 Switch' 1"
		cset "name='TX_DEC0 Volume' 84"
	]

	DisableSequence [
		cset "name='ADC1_MIXER Switch' 0"
		cset "name='ADC1 Switch' 0"
	]

	Value {
		CaptureChannels 1
		CapturePriority 200
		CapturePCM "hw:${CardId},2"
		CaptureMixerElem "ADC1"
		CaptureVolume "ADC1 Volume"
	}
}

SectionDevice."Mic3" {
	Comment "Bottom Microphone"

	ConflictingDevice [
		"Mic1"
	]

	Include.txmhpe.File "/codecs/qcom-lpass/tx-macro/SoundwireMic4EnableSeq.conf"
	Include.txmhpd.File "/codecs/qcom-lpass/tx-macro/SoundwireMicDisableSeq.conf"

	EnableSequence [
		cset "name='ADC2 Switch' 1"
		cset "name='ADC2_MIXER Switch' 1"
		cset "name='ADC2 MUX' INP3"
	]

	DisableSequence [
		cset "name='ADC2_MIXER Switch' 0"
		cset "name='ADC2 Switch' 0"
	]

	Value {
		CaptureChannels 1
		CapturePriority 200
		CapturePCM "hw:${CardId},2"
		CaptureMixerElem "ADC2"
		CaptureVolume "ADC2 Volume"
	}
}
