# Use case configuration for Fairphone 5
# Author: Luca Weiss <luca.weiss@fairphone.com>

Syntax 3

LibraryConfig.remap.Config {
	ctl.default.map."name='Amplifier Playback Volume'" {
		"name='Amplifier L PCM Playback Volume'".vindex.0 0
		"name='Amplifier R PCM Playback Volume'".vindex.1 0
	}
}

SectionUseCase."HiFi" {
	File "/Fairphone/fp5/HiFi.conf"
	Comment "HiFi quality Music."
}
